on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
    ignore:
      - "[skip ci]"
      - "[ci skip]"

name: Build My Apps

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    name: Build and Release new apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Decode Google Services JSON
        id: decode
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: "google-services.json"
          encodedString: ${{ secrets.GOOGLE_SERVICES_JSON }}

      - name: Move google-services.json
        run: mv ${{ steps.decode.outputs.filePath }} android/app/google-services.json

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: "upload-keystore.jks"
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Move Keystore to Android app directory
        run: mv ${{ steps.decode_keystore.outputs.filePath }} android/app/upload-keystore.jks

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Extract version from pubspec.yaml
        id: extract_version
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | sed 's/version: //')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/app/outputs/flutter-apk/app-release.apk
          tag: ${{ env.VERSION }}
          token: ${{ secrets.TOKEN }}
